In [35]:
import numpy as np

In [36]:
arr = np.arange(12).reshape(3, 4)

In [37]:
arr.cumprod(axis=1)

array([[   0,    0,    0,    0],
       [   4,   20,  120,  840],
       [   8,   72,  720, 7920]], dtype=int32)

In [38]:
arr.cumprob(axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'cumprob'

In [ ]:
from numpy.linalg import inv, qr

In [ ]:
import numpy as np

In [ ]:
x = np.random.rand(5, 5)

In [ ]:
mat = x.T.dot(x)

In [ ]:
mat

In [39]:
inv(mat)

array([[ 6.62960952e+02,  3.71059799e+04,  5.60174618e+02,
        -2.93610470e+04, -1.14997367e+04],
       [ 3.71059799e+04,  2.09259731e+06,  3.16361372e+04,
        -1.65576415e+06, -6.48298558e+05],
       [ 5.60174618e+02,  3.16361372e+04,  4.79792430e+02,
        -2.50330378e+04, -9.80053797e+03],
       [-2.93610470e+04, -1.65576415e+06, -2.50330378e+04,
         1.31012333e+06,  5.12964713e+05],
       [-1.14997367e+04, -6.48298558e+05, -9.80053797e+03,
         5.12964713e+05,  2.00851809e+05]])

In [40]:
q, r = qr(mat)

In [41]:
q

array([[-0.53106211,  0.64262454,  0.08000849, -0.54628081, -0.01351514],
       [-0.44486387, -0.37865141,  0.27578918,  0.04628124, -0.76191707],
       [-0.41698615, -0.11926461, -0.89082649,  0.13488515, -0.01151815],
       [-0.42126984, -0.58333399,  0.22840755, -0.25814114,  0.60286509],
       [-0.41075959,  0.29858705,  0.26794986,  0.78396714,  0.23605239]])

In [42]:
r

array([[-4.59377687e+00, -4.27851480e+00, -4.18846955e+00,
        -4.16312258e+00, -3.64496037e+00],
       [ 0.00000000e+00, -3.55653609e-01, -3.96186469e-01,
        -4.70248082e-01,  3.36985210e-02],
       [ 0.00000000e+00,  0.00000000e+00, -6.77390814e-01,
        -6.35625308e-02,  1.29283421e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -5.78850179e-02,  1.47839125e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.17525646e-06]])

In [43]:
arr = np.random.randn(5, 5)

In [44]:
arr

array([[-0.46930528,  0.34844733,  0.11661754,  1.2991196 , -0.16398928],
       [-0.83204799,  0.59690015,  1.14442045,  0.87628003,  0.49893736],
       [-2.15153411,  0.93618632,  1.28670118,  0.46657928,  1.6096104 ],
       [-0.33702046,  0.59211112,  0.30171403,  0.88773073, -0.3124888 ],
       [ 0.45351887,  0.99039709,  0.53238534,  1.15444673,  1.58114401]])

In [45]:
seed = np.random.seed(1234)

In [46]:
seed.randn(5, 5)

AttributeError: 'NoneType' object has no attribute 'randn'

In [ ]:
arr2 = np.random.randn(5, 5)
arr2

In [ ]:
import random

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
positions = 0
walk = [positions]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    positions += step
    walk.append(positions)

In [ ]:
plt.plot(walk[:100])

In [ ]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0,2,size=(nwalks,nsteps))
steps= np.where(draws >0, 1,-1)
walk = steps.cumsum(1)

In [ ]:
plt.plot(walk[:10,:100])

In [ ]:
walk.min(1)

In [50]:
hit30 = (np.abs(walk)>=30).any(1)
crossing_times = (np.abs(walk[hit30]>=30)).argmax(1)

In [51]:
crossing_times.mean()

255.6193720379147